export const Homeitems = [
  {
    image: "assets/homePage1.jpg",
    alt: "homePage1Img",
    pageHeading: "just push.",
    homeText: "headLine",
    className: "homePageImg1",
  },
  {
    image: "assets/homePage2.jpg",
    alt: "homePage2Img",
    pageHeading: "about",
    homeText: "aboutLine",
    className: "homePageImg2",
    image2: "assets/skateshopinside.jpg",
    alt2: "inside",
    className2: "insideImg",
    textDiv: "aboutDiv",
    textStyle: "aboutStyle",
    text: "Welcome to Just Push, the ultimate skate shop crafted by skaters, for skaters. Born out of a shared passion for skateboarding, our store is more than just a place to buy gear—it's a hub for the skating community. Here, you'll find a curated selection of top-quality skateboards, apparel, and accessories, all handpicked by enthusiasts who understand what skaters need. At Just Push, we pride ourselves on offering expert advice, personalized service, and an environment where every skateboarder feels at home. Whether you're a seasoned pro or just starting out, our team is here to help you push your limits and ride with style. Join us at Just Push, where the skate culture thrives and every push counts.",
  },
  {
    image: "assets/homePage3.jpg",
    alt: "homePage3Img",
    pageHeading: "where to find us",
    homeText: "locationLine",
    className: "homePageImg3",
    image2: "assets/location.png",
    alt2: "location",
    className2: "locationImg",
  },
];
