const storeItems = [
  {
    id: 1,
    name: "Creature",
    group: "Decks",
    description: "PSYCHO LOGO DECK",
    price: "R1799",
    imageUrl: "assets/deck1.webp",
  },

  {
    id: 2,
    name: "Anti Hero",
    group: "Decks",
    description: "PFANNER WILD UNKNOWN DECK",
    price: "R1899",
    imageUrl: "assets/deck4.webp",
  },

  {
    id: 3,
    name: "Uma Landsleds",
    group: "Decks",
    description: "ROMAN BLUR DECK",
    price: "R1699",
    imageUrl: "assets/deck6.webp",
  },
  {
    id: 4,
    name: "Anti Hero",
    group: "Decks",
    description: "BA MEDICINE DECK",
    price: "R1599",
    imageUrl: "assets/deck2.webp",
  },

  {
    id: 1,
    name: "Venture",
    group: "Trucks",
    description: "ALL POLISHED LOW TRUCKS(PAIR)",
    price: "R1099",
    imageUrl: "assets/trucks1.webp",
  },

  {
    id: 2,
    name: "Thunder",
    group: "Trucks",
    description: "POLISHED HOLLOW II TRUCKS(PAIR)",
    price: "R1799",
    imageUrl: "assets/trucks2.webp",
  },
  {
    id: 3,
    name: "Thunder",
    group: "Trucks",
    description: "POLISHED HIGH TRUCKS(PAIR)",
    price: "R1299",
    imageUrl: "assets/trucks3.webp",
  },
  {
    id: 4,
    name: "Independent",
    group: "Trucks",
    description: "SILVERFORGED HOLLOW TRUCKS(PAIR)",
    price: "R1299",
    imageUrl: "assets/trucks4.webp",
  },

  {
    id: 1,
    name: "Spitfire",
    group: "Wheels",
    description: "80HD CONICAL FULL",
    price: "R1299",
    imageUrl: "assets/wheels1.webp",
  },

  {
    id: 2,
    name: "Spitfire",
    group: "Wheels",
    description: "FORMULA 4 99D RADIAL WHEELS",
    price: "R1099",
    imageUrl: "assets/wheels2.webp",
  },
  {
    id: 3,
    name: "Spitfire",
    group: "Wheels",
    description: "FORMULA 4 101D BURN WHEELS",
    price: "R1199",
    imageUrl: "assets/wheels3.webp",
  },
  {
    id: 4,
    name: "Spitfire",
    group: "Wheels",
    description: "FORMULA 4 99D BURN WHEELS",
    price: "R899",
    imageUrl: "assets/wheels4.webp",
  },
  {
    id: 1,
    name: "Bones",
    group: "Bearings",
    description: "REDS BIG BALL BEARINGS",
    price: "R699",
    imageUrl: "assets/bearings1.webp",
  },

  {
    id: 2,
    name: "Bones",
    group: "Bearings",
    description: "SUPER RED BEARINGS",
    price: "R799",
    imageUrl: "assets/bearings2.webp",
  },
  {
    id: 3,
    name: "Bronson",
    group: "Bearings",
    description: "G2 BEARINGS",
    price: "R399",
    imageUrl: "assets/bearings3.webp",
  },
  {
    id: 4,
    name: "Bronson",
    group: "Bearings",
    description: "G3 BEARINGS",
    price: "R599",
    imageUrl: "assets/bearings4.webp",
  },
  {
    id: 1,
    name: "Anti Hero",
    group: "Completes",
    description: "CLASSIC EAGLE II COMPLETE",
    price: "R1599",
    imageUrl: "assets/complete1.webp",
  },

  {
    id: 2,
    name: "Krooked",
    group: "Completes",
    description: "OG SWEATPANTS COMPLETE",
    price: "R1599",
    imageUrl: "assets/complete2.webp",
  },

  {
    id: 3,
    name: "Krooked",
    group: "Completes",
    description: "SWEATPANTS II COMPLETE",
    price: "R1599",
    imageUrl: "assets/complete3.webp",
  },

  {
    id: 4,
    name: "REAL",
    group: "Completes",
    description: "BE FREE FADE",
    price: "R1599",
    imageUrl: "assets/complete4.webp",
  },
  {
    id: 1,
    name: "NIKE SB",
    group: "SHOES",
    description: "DUNK HIGH PRO SHOES",
    price: "R1999",
    imageUrl: "assets/shoe1.webp",
  },

  {
    id: 2,
    name: "NIKE SB",
    group: "SHOES",
    description: "DUNK HIGH LOW SHOES",
    price: "R2299",
    imageUrl: "assets/shoe2.webp",
  },
  {
    id: 3,
    name: "VANS",
    group: "SHOES",
    description: "SKATE HALF CAB SHOES",
    price: "R1599",
    imageUrl: "assets/shoe3.webp",
  },
  {
    id: 4,
    name: "VANS",
    group: "SHOES",
    description: "SKATE OLD SKOOL SHOES",
    price: "R1250",
    imageUrl: "assets/shoe4.webp",
  },
];

export default storeItems;
